install:
  - choco install gitversion.portable -pre -y
  
before_build:  
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

build:
  project: dbup-diy-cli.sln

configuration: Release

after_build:
  - .paket\paket.exe pack output nugets include-referenced-projects version %GitVersion_NuGetVersion%

artifacts:
  - path: 'nugets\*.nupkg'

cache:
  - packages -> paket.lock
  
deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true