before_build:
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

build_script:
  - ps: dotnet pack -c Release -o ../../nugets

artifacts:
  - path: 'nugets\*.nupkg'

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true