install:
  - choco install gitversion.portable -y

before_build:
  - dotnet restore
  - ps: gitversion /l console /output buildserver

build:
  project: dbup-diy-cli.sln

configuration: Release

after_build:
  - dotnet pack output -o nugets

artifacts:
  - path: 'nugets\*.nupkg'

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true